name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # -----------------------------------
      # 1. Checkout repository
      # -----------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------------
      # 2. Install Miniforge (clean)
      # -----------------------------------
      - name: Set up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          use-mamba: false          # keep classic conda for reliability
          auto-activate-base: false

      # -----------------------------------
      # 3. Create environment from environment.yml
      # -----------------------------------
      - name: Create conda environment
        run: |
          conda env create -f environment.yml
          conda activate fakect
          conda info
          conda list

      # -----------------------------------
      # 4. Install package in editable mode
      # -----------------------------------
      - name: Install package
        run: |
          conda run -n fakect pip install -e .

      # -----------------------------------
      # 5. Run tests (basic)
      # -----------------------------------
      - name: Run pytest
        run: |
          conda run -n fakect pytest -v
